from dotenv import load_dotenv
load_dotenv()

import json
from openai import OpenAI
from pydantic import BaseModel

default_gpt_model="gpt-5.4-mini"
client = OpenAI()

def tool_basic():
    tools = [
        {
            "type": "function",
            "name": "get_horoscope",
            "description": "Get today's horoscope for an astrological sign.",
            "parameters": {
                "type": "object",
                "properties": {
                    "sign": {
                        "type": "string",
                        "description": "An astrological sign like Taurus or Aquarius",
                    },
                },
                "required": ["sign"],
            },
        },
    ]

    def get_horoscope(sign):
        return f"{sign}: Next Tuesday you will be friend a baby otter."
    
    input_list = [
        {"role": "user", "content": "What is my horoscope? I am an Aquarius."}
    ]

    response = client.responses.create(
        model="gpt-5",
        tools=tools,
        input=input_list,
    )

    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_horoscope":
                sign = json.loads(item.arguments)["sign"]
                horoscope = get_horoscope(sign)
                
                # 4. Provide function call results to the model
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": horoscope,
                })
    
    print("Final input:")
    print(input_list)

    response = client.responses.create(
        model="gpt-5",
        instructions="Respond only with a horoscope generated by a tool.",
        tools=tools,
        input=input_list,
    )

    # 5. The model should be able to give a response!
    print("Final output:")
    print(response.model_dump_json(indent=2))
    print("\n" + response.output_text)

if __name__ == "__main__":
    tool_basic()