from dotenv import load_dotenv
load_dotenv()

import json
from openai import OpenAI
from pydantic import BaseModel

default_gpt_model="gpt-5.4-mini"
client = OpenAI()

def tool_basic():
    tools = [
        {
            "type": "function",
            "name": "get_horoscope",
            "description": "Get today's horoscope for an astrological sign.",
            "parameters": {
                "type": "object",
                "properties": {
                    "sign": {
                        "type": "string",
                        "description": "An astrological sign like Taurus or Aquarius",
                    },
                },
                "required": ["sign"],
            },
        },
    ]

    def get_horoscope(sign):
        return f"{sign}: Next Tuesday you will be friend a baby otter."
    
    input_list = [
        {"role": "user", "content": "What is my horoscope? I am an Aquarius."}
    ]

    response = client.responses.create(
        model="gpt-5",
        tools=tools,
        input=input_list,
    )

    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_horoscope":
                sign = json.loads(item.arguments)["sign"]
                horoscope = get_horoscope(sign)
                
                # 4. Provide function call results to the model
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": horoscope,
                })
    
    print("Final input:")
    print(input_list)

    response = client.responses.create(
        model="gpt-5",
        instructions="Respond only with a horoscope generated by a tool.",
        tools=tools,
        input=input_list,
    )

    # 5. The model should be able to give a response!
    print("Final output:")
    print(response.model_dump_json(indent=2))
    print("\n" + response.output_text)

def tool_stream():
    tools = [{
        "type": "function",
        "name": "get_weather",
        "description": "Get current temperature for a given location.",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "City and country e.g. Bogotá, Colombia"
                }
            },
            "required": [
                "location"
            ],
            "additionalProperties": False
        }
    }]

    stream = client.responses.create(
        model=default_gpt_model,
        input=[{"role": "user", "content": "What's the weather like in Paris today?"}],
        tools=tools,
        stream=True
    )

    for event in stream:
        print(event)

def tool_custom():
    tools = [
        {
            "type": "custom",
            "name": "code_exec",
            "description": "Executes arbitrary Python code.",
        }
    ]

    response = client.responses.create(
        model=default_gpt_model,
        input="Use the code_exec tool to print hello world to the console.",
        tools=tools
    )

    print(response.output)

def tool_custom_lark():
    grammar = """
    start: expr
    expr: term (SP ADD SP term)* -> add
    | term
    term: factor (SP MUL SP factor)* -> mul
    | factor
    factor: INT
    SP: " "
    ADD: "+"
    MUL: "*"
    %import common.INT
    """

    tools = [
        {
            "type": "custom",
            "name": "math_exp",
            "description": "Creates valid mathematical expressions",
            "format": {
                "type": "grammar",
                "syntax": "lark",
                "definition": grammar
            }
        }
    ]

    response = client.responses.create(
        model=default_gpt_model,
        input="Use the math_exp tool to add four plus four.",
        tools=tools
    )

    print(response.output)

def tool_custom_regex():
    grammar = r"^(?P<month>January|February|March|April|May|June|July|August|September|October|November|December)\s+(?P<day>\d{1,2})(?:st|nd|rd|th)?\s+(?P<year>\d{4})\s+at\s+(?P<hour>0?[1-9]|1[0-2])(?P<ampm>AM|PM)$"

    tools = [
        {
            "type": "custom",
            "name": "timestamp",
            "description": "Saves a timestamp in date + time in 24-hr format.",
            "format": {
                "type": "grammar",
                "syntax": "regex",
                "definition": grammar
            }
        }
    ]

    response = client.responses.create(
        model=default_gpt_model,
        input="Use the timestamp tool to save a timestamp for August 7th 2025 at 10AM.",
        tools=tools
    )

    print(response.output)

if __name__ == "__main__":
    # tool_basic()
    # tool_stream()
    # tool_custom()
    # tool_custom_lark()
    tool_custom_regex()